dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
      env:
        - CC=gcc-8
        - CXX=g++-8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libgl1-mesa-dev libsdl2-dev
  
install:
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-linux.tar.gz -O premake.tar.gz
  - tar -xf premake.tar.gz
  - ./premake5 shaders
  - ./premake5 gmake
  - cd build

script:
  make config=release_x86_64
  
before_deploy:
  tar pczf renderer_bgfx_x86_64.tar.gz --directory="bin_x64" renderer_bgfx_x86_64.so
  
deploy:
  skip_cleanup: true
  provider: bintray
  file: ../.bintray.json
  user: jpcy
  key: $BINTRAY_API_KEY
  
notifications:
  email: false
